### ISSUE TITLE
How to name the API that is gonna hold the all the frameworks?

### ISSUE THREAD

**Issue by ZenMaster91** [computer-engineering-uniovi/swift#3]
@mistermboy Hey! Propose names to name the main API, like willyOS but without the OS (it's not an Operative System).
_You can do it by angering to this issue._

**Comment by mistermboy** [comment]
M&W

**Comment by ZenMaster91** [comment]
🤔... Not really a good name I think...
What if someone else joins the dev team?
Is the char `&` safe?

**Comment by ZenMaster91** [comment]
What about Darwin? Like the father of evolution?

**Comment by mistermboy** [comment]
jajjajaja
oh sorry, I wanted to say:
hahaha
It´s the same but in English.
Darwing it´s ok, but my beliefs speak about a creator. So.. I prefer DarthWing
